// src/components/DeviceDetails.vue
<template>
  <div class="bg-white p-6 rounded-lg shadow-md">
    <h2 class="text-xl font-semibold mb-4">{{ device.device_name }}</h2>
    <div class="grid grid-cols-2 gap-4 mb-4">
      <div class="flex items-center">
        <Cpu class="text-blue-500 mr-2" :size="20" />
        <span>Status: {{ device.status }}</span>
      </div>
      <div class="flex items-center">
        <Battery class="text-green-500 mr-2" :size="20" />
        <span>Product: {{ device.product_name }}</span>
      </div>
      <div v-if="device.secret" class="col-span-2 flex items-center">
        <Thermometer class="text-red-500 mr-2" :size="20" />
        <span>Secret: {{ device.secret }}</span>
      </div>
    </div>
    <div class="flex justify-end space-x-2">
      <button
        @click="toggleDeviceStatus"
        :class="`px-3 py-1 rounded ${
          device.status === 'active' ? 'bg-yellow-500 hover:bg-yellow-600' : 'bg-green-500 hover:bg-green-600'
        } text-white`"
      >
        <Pause v-if="device.status === 'active'" :size="20" />
        <Play v-else :size="20" />
      </button>
      <button
        @click="deleteDevice"
        class="bg-red-500 text-white px-3 py-1 rounded hover:bg-red-600"
      >
        <Trash2 :size="20" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Cpu, Battery, Thermometer, Trash2, Play, Pause } from 'lucide-vue-next';

const props = defineProps<{
  device: {
    product_name: string;
    device_name: string;
    status: 'active' | 'suspended';
    secret?: string;
  };
  apiUrl: string;
}>();

const emit = defineEmits(['device-updated']);

const toggleDeviceStatus = async () => {
  const action = props.device.status === 'active' ? 'suspend' : 'resume';
  try {
    await fetch(`${props.apiUrl}/devices/${props.device.product_name}/${props.device.device_name}/${action}`, {
      method: 'PUT',
    });
    emit('device-updated');
  } catch (error) {
    console.error(`Error ${action}ing device:`, error);
  }
};

const deleteDevice = async () => {
  try {
    await fetch(`${props.apiUrl}/devices/${props.device.product_name}/${props.device.device_name}`, {
      method: 'DELETE',
    });
    emit('device-updated');
  } catch (error) {
    console.error('Error deleting device:', error);
  }
};
</script>

// src/components/DeviceDetails.tsx
import React, { useEffect } from 'react';
import { Cpu, Battery, Key, Trash2, Play, Pause, Clock, Lock, Unlock } from 'lucide-react';
import { Device } from '../App';

interface DeviceDetailsProps {
  device: Device;
  apiUrl: string;
  onDeviceUpdate: () => void;
  onDeviceDelete: () => void;
}

const DeviceDetails: React.FC<DeviceDetailsProps> = ({ device, apiUrl, onDeviceUpdate, onDeviceDelete }) => {
  const toggleDeviceStatus = async () => {
    const action = device.status === 'active' ? 'suspend' : 'resume';
    try {
      const response = await fetch(`${apiUrl}/devices/${device.product_name}/${device.device_name}/${action}`, {
        method: 'PUT',
      });
      if (response.ok) {
        await updateDeviceStatus(); // 立即更新设备状态
      } else {
        console.error('切换设备状态失败');
      }
    } catch (error) {
      console.error(`切换设备状态时出错:`, error);
    }
  };

  const deleteDevice = async () => {
    try {
      await fetch(`${apiUrl}/devices/${device.product_name}/${device.device_name}`, {
        method: 'DELETE',
      });
      onDeviceDelete();
      await updateDeviceStatus(); // 立即更新设备状态
    } catch (error) {
      console.error('删除设备时出错:', error);
    }
  };

  const updateDeviceStatus = async () => {
    try {
      const response = await fetch(`${apiUrl}/devices/${device.product_name}/${device.device_name}/status`, {
        method: 'PUT',
      });
      if (response.ok) {
        onDeviceUpdate(); // 在成功更新状态后调用更新
      } else {
        console.error('更新设备状态失败');
      }
    } catch (error) {
      console.error(`更新设备状态时出错:`, error);
    }
  };

  useEffect(() => {
    const intervalId = setInterval(() => {
      updateDeviceStatus();
    }, 5000); // 每5秒更新一次状态

    return () => clearInterval(intervalId); // 组件卸载时清除定时器
  }, [device.product_name, device.device_name]);

  return (
    <div className="bg-white p-6 rounded-lg shadow-md">
      <h2 className="text-xl font-semibold mb-4">设备ID:{device.device_name}</h2>
      <div className="grid grid-cols-2 gap-4 mb-4">
        <div className="flex items-center">
          <Cpu className="text-blue-500 mr-2" size={20} />
          <span>激活状态: {device.status}</span>
        </div>
        <div className="flex items-center">
          <Battery className="text-green-500 mr-2" size={20} />
          <span>产品: {device.product_name}</span>
        </div>
        {device.secret && (
          <div className="col-span-2 flex items-center">
            <Key className="text-red-500 mr-2" size={20} />
            <span>密钥: {device.secret}</span>
          </div>
        )}
        <div className="col-span-2 flex items-center">
          <Clock className="text-purple-500 mr-2" size={20} />
          <span>最后状态更新: {new Date(device.last_status_update).toLocaleString()}</span>
        </div>
        <div className="col-span-2 flex items-center">
          <span>在线状态: {device.connected ? '在线' : '离线'}</span>
        </div>
      </div>
      <div className="flex justify-end space-x-2">
        <button
          onClick={updateDeviceStatus}
          className="bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-600"
        >
          更新状态
        </button>
        <button
          onClick={toggleDeviceStatus}
          className={`px-3 py-1 rounded ${
            device.status === 'active' ? 'bg-yellow-500 hover:bg-yellow-600' : 'bg-green-500 hover:bg-green-600'
          } text-white`}
        >
          {device.status === 'active' ? <Lock size={20} /> : <Unlock size={20} />}
        </button>
        <button
          onClick={deleteDevice}
          className="bg-red-500 text-white px-3 py-1 rounded hover:bg-red-600"
        >
          <Trash2 size={20} />
        </button>
      </div>
    </div>
  );
};

export default DeviceDetails;
